### ISSUE TITLE
task every45minutes unnecessary second start

### ISSUE THREAD

**Issue by Karmashkin** [gjcarneiro/yacron#16]
yacron run inside docker alpine 3.6 based
python 3.6.1
timezone in the container and on the host is the same.

The report 'onSuccess' comes two times, 45 minutes and 15 minutes after that.
in other words, the task runs twice per hour

crontab.yaml
```
defaults:
  captureStderr: true
  captureStdout: true
  onFailure:
    report:
      mail:
        from: cron@xxxx.xxx
        to: xxx@xxxx.xxx
        smtpHost: xxxxxxxx
        subject: Cron job '{{name}}' {% if success %}completed{% else %}failed{% endif %}
        body: |
          command: {{command}}
          shell: {{shell}}
          environment: {{environment}}
          STDOUT: {{stdout}}
          STDERR: {{stderr}}
          exit code: {{exit_code}}

jobs:
- name: 45minutes
  command: /usr/bin/php5 /xxx/xxx/xxx.php
#  schedule: "*/45 * * * *"
  schedule:
    minute: "*/45"
  onSuccess:
    report:
      mail:
        from: cron@xxxx.xxx
        to: xxx@xxxx.xxx
        smtpHost: xxxxxxxx

```
