### ISSUE TITLE
Feature request: logging reporter

### ISSUE THREAD

**Issue by Nekmo** [gjcarneiro/yacron#33]
Hi,

I would like to write the successful executions to a file, but I think it would be better to support logging to configure logs. In the Python documentation there is an example in Yaml:

https://docs.python.org/3/howto/logging.html#configuring-logging
https://docs.python.org/3/library/logging.config.html#dictionary-schema-details

It is only necessary to configure a handler and a format. Loggers can be dynamically created from jobs. 

My proposal:
```yaml
- name: test-01
  command: |
    echo "hello" 1>&2
    sleep 1
    exit 10
  schedule:
    minute: "*/2"
  captureStderr: true
  onFailure:
    report:
      logging:
      	format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      	handler:
      	  class: logging.StreamHandler
          stream: ext://sys.stdout
```

Supporting the logging module allows to use many other handlers such as rsyslog.
