### ISSUE TITLE
Sentry: fingerprint option doesn't appear to be working

### ISSUE THREAD

**Issue by gjcarneiro** [gjcarneiro/yacron#52]
* Yet Another Cron version: 0.13 (binary)
* Python version: 3.8
* Operating System: ubuntu

Based on production use, running in Kubernetes, a cron jobs that fails creates an Issue in Sentry.  When the pod is replaced by a new pod, which changes its hostname, the failing cron job will then create a new Issue in Sentry.  Even though I have this in the config:

```yaml
  onFailure:
    report:
      sentry:
        dsn:
          fromEnvVar: SENTRY_DSN
        fingerprint:
          - yacron
          - "{{ name }}"
```

It's as if the fingerprint is being ignored and instead the default sentry_sdk fingerprint is being used instead...

Might have been broken by some sentry_sdk upgrade.  Needs debugging.
