### ISSUE TITLE
Email / Sentry reporting: jinja2 templating

### ISSUE THREAD

**Issue by gjcarneiro** [gjcarneiro/yacron#8]
As a final feature before a 1.0 release, I'd would like to have the reports more customisable, using jinja2 as templating language.  Namely, the "subject" and "body" of the reporting would have the possibility of being customised.
```yaml
  onPermanentFailure:
    report:
      sentry:
         dsn:
           value: xxxxx
      title: "job {{name}} has failed"
      body: |
          The cron job {{name}} has failed with status {{status}}
          STDOUT:
          ------------
          {{stdout}}

          STDERR:
          ------------
          {{stderr}}
```
