### ISSUE TITLE
Web startup message goes to stderr?

### ISSUE THREAD

**Issue by andrewplummer** [gjcarneiro/yacron#96]
* Yet Another Cron version: 0.19.0
* Python version: 3.9.19

### Description

Apologies in advance as I feel like I'm misunderstanding something here but no matter what I try the initial web message:

> INFO:yacron:web: started listening on http://127.0.0.1:8080

Always seems to go to stderr. This causes false positives in the logs (using GCP in our case).

Dockerfile:

```Dockerfile
# Use an appropriate base image
FROM python:3.9-slim

RUN pip install yacron pyyaml

# Copy your yacron configuration file into the container
COPY . .

# Copy the entrypoint script into the container
COPY entrypoint.sh /root/entrypoint.sh
RUN chmod +x /root/entrypoint.sh

# Set the working directory
WORKDIR .

# Set the entrypoint to the script
ENTRYPOINT ["/bin/sh", "-c", "/usr/local/bin/yacron -c test.yml 2>err.txt"]

```

and config:

```yml
web:
  listen:
    - http://127.0.0.1:8080
    - unix:///tmp/yacron.sock

defaults:
  shell: /bin/bash

  concurrencyPolicy: Allow
  # Allow (default): allows concurrently running jobs
  # Forbid: forbids concurrent runs, skipping next run if previous hasn’t finished yet
  # Replace: cancels currently running job and replaces it with a new one

  failsWhen:
    producesStdout: false
    producesStderr: true
    nonzeroReturn: true

  onPermanentFailure:
    report:
      sentry:
        dsn:
          value:
        extra:
          foo: bar
          zbr: 123
        level: warning
      mail:
        from: example@foo.com
        to: example@bar.com
        smtpHost: 127.0.0.1
        smtpPort: 10025
        subject: Cron job '{{name}}' {% if success %}completed{% else %}failed{% endif %}
        body: |
          {{stderr}}

          (exit code: {{exit_code}})

  environment:
    - key: FOO
      value: foo
    - key: BAR
      value: bar

  statsd:
    host: localhost
    port: 8125
    prefix: my.cron.jobs.prefix.test01

logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    simple:
      format: '%(asctime)s [%(processName)s/%(threadName)s] %(levelname)s (%(name)s): %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
  root:
    level: INFO
    handlers:
      - console
  loggers:
    yacron:
      level: INFO
      handlers:
        - console
      propagate: false

```

With this config as a test the `err.txt` should contain the initial startup message. Despite claiming `INFO` it seems that it was sent to stderr.
